server:
  port: 8080
  servlet:
    context-path: /poc

spring:
  profiles:
    active: ${PROFILES_ACTIVE}
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

management:
  endpoint:
    health:
      show-components: always
    endpoints:
      web:
        exposure:
          include: actuator, logfile, metrics, health, info
        base-path: /v1/actuator

cloud:
  aws:
    credentials:
      access-key: localstack
      secret-key: localstack
    region:
      static: sa-east-1
    stack:
      auto: false

sqs:
  endpoint: http://localhost:4566
  queue:
    envia-documento: http://localhost:4566/000000000000/sqs-envia-documento-service-queue-loc
    dlq-envia-documento: http://localhost:4566/000000000000/sqs-dlq-envia-documento-service-queue-loc
