version: '3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs
      - DATA_DIR=/tmp/localstack/data
